language: cpp
sudo: required
dist: trusty

common_sources: &all_sources
  - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      addons:
        apt:
         sources: ['ubuntu-toolchain-r-test']
         packages: ['g++-4.8']
      env: 
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

    - os: linux
      addons:
        apt:
          sources: *all_sources
          packages: ['g++-4.9']
      env: 
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources: *all_sources
          packages: ['g++-5']
      env: 
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons: &gcc6
        apt:
          sources: *all_sources
          packages: ['g++-6']
      env: 
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons: &gcc7
        apt:
          sources: *all_sources
          packages: ['g++-7']
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons: *gcc6
      env: 
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 CPP14=1"

    - os: linux
      addons: *gcc7
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 CPP14=1"

before_script:
   - eval "${MATRIX_EVAL}"
   - env
   - export CC_FOR_BUILD=$CC
   - export CXX_FOR_BUILD=$CXX
script:
  - cmake . -Dbrynet_BUILD_EXAMPLES=ON -Dbrynet_BUILD_TESTS=ON
  - make
  - cd tests && ctest -V